# Kmeans
- unsupervised learning algorithm

In [14]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import imutils

In [10]:
X = np.random.randint(25,50,(25,2))
Y = np.random.randint(60,85,(25,2))
Z = np.vstack((X,Y))

In [11]:
Z.dtype

dtype('int32')

In [12]:
Z = np.asfarray(Z, dtype=np.float32)

In [13]:
Z.dtype

dtype('float32')

> - cv는 float32만 지원하므로 dtype을 바꿔줘야한다.
- `np.float32`를 쓸 수도 있지만, `astype`으로 바꾸는 것이 더 효율적이다.
- 속도가 쬐끔 차이가 난다.

In [15]:
imutils.find_function("kmeans")

1. BOWKMeansTrainer
2. KMEANS_PP_CENTERS
3. KMEANS_RANDOM_CENTERS
4. KMEANS_USE_INITIAL_LABELS
5. kmeans


In [16]:
imutils.find_function("criteria")

1. TERM_CRITERIA_COUNT
2. TERM_CRITERIA_EPS
3. TERM_CRITERIA_MAX_ITER
4. TermCriteria_COUNT
5. TermCriteria_EPS
6. TermCriteria_MAX_ITER


In [38]:
cv2.TERM_CRITERIA_COUNT, cv2.TERM_CRITERIA_EPS, cv2.TERM_CRITERIA_MAX_ITER

(1, 2, 1)

> - 상수값을 확인해보니 `TERM_CRITERIA_COUNT`와 `TERM_CRITERIA_MAX_ITER`가 같다.
- 대문자 상수가 나오면 반드시 찍어보도록 하자.
- 2의 배수이면 switch 기ㅂ

In [20]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0) 
ret, label, center = cv2.kmeans(Z, 2, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)

> criteria = (상수, 반복회수, 수렴제한) 

In [31]:
ret

6057.519944690168

In [32]:
label

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int32)

In [33]:
center

array([[36.12    , 37.04    ],
       [71.439995, 71.64    ]], dtype=float32)

In [37]:
criteria = (3, 10, 1.0)
cv2.kmeans(Z, 2, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)


(6057.519944690168, array([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0]], dtype=int32), array([[71.439995, 71.64    ],
        [36.12    , 37.04    ]], dtype=float32))

In [40]:
cv2.KMEANS_PP_CENTERS, cv2.KMEANS_RANDOM_CENTERS, cv2.KMEANS_USE_INITIAL_LABELS

(2, 0, 1)

# sklearn에서 해보기

In [46]:
import seaborn as sns
iris = sns.load_dataset("iris")

In [41]:
from sklearn.cluster import KMeans, DBSCAN

### DBSCAN
scikit-learn

In [53]:
dbs = DBSCAN(min_samples=20)

> - 조건을 주면 최적의 클러스터개수를 반환함
- `min_sample`은 클러스터의 최소 값 개수

In [51]:
dbs.fit(iris.iloc[:,:-1])

DBSCAN(algorithm='auto', eps=0.5, leaf_size=30, metric='euclidean',
       metric_params=None, min_samples=20, n_jobs=None, p=None)

In [52]:
vars(dbs)

{'eps': 0.5,
 'min_samples': 20,
 'metric': 'euclidean',
 'metric_params': None,
 'algorithm': 'auto',
 'leaf_size': 30,
 'p': None,
 'n_jobs': None,
 'core_sample_indices_': array([ 0,  2,  4,  6,  7,  9, 11, 17, 19, 21, 26, 27, 28, 29, 30, 34, 35,
        39, 40, 46, 47, 48, 49], dtype=int64),
 'labels_': array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,
         0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       dtype=int64)

### KMeans
scikit-learn

In [57]:
kme = KMeans(3)

In [58]:
kme.fit_predict(iris.iloc[:,:-1])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1])

> - cv의 kmeans를 쓰는 이유?
    - 시스템화, 서비스에 좋다.
- scikit-learn은 분석 까지만!

---

# SVM
- 한때 잘 나갔던 알고리즘
- 정교한 성능/극악의 속도
- 아직 사용하는 곳도 있다.
- outlier detection할 때 사용되고 있다.

In [59]:
# data creating
labels = np.array([1,-1,-1,-1])
trainingData = np.matrix([[501, 10], [255, 10], [501, 255], [10, 501]], dtype=np.float32)

In [60]:
# model
svm = cv2.ml.SVM_create()

In [65]:
[_ for _ in dir(svm) if _.startswith("set")]

['setC',
 'setClassWeights',
 'setCoef0',
 'setDegree',
 'setGamma',
 'setKernel',
 'setNu',
 'setP',
 'setTermCriteria',
 'setType']

> - set으로 시작하면 선택가능한 옵션
    - scikit으로 치면 하이퍼 파라미터이다.

In [62]:
# options
svm.setType(cv2.ml.SVM_C_SVC)
svm.setKernel(cv2.ml.SVM_LINEAR)
svm.setTermCriteria((cv2.TERM_CRITERIA_MAX_ITER, 100, 1e-6))

In [63]:
# train
svm.train(trainingData, cv2.ml.ROW_SAMPLE, labels)

True

In [68]:
# predict
svm.predict(trainingData)

(0.0, array([[ 1.],
        [-1.],
        [-1.],
        [-1.]], dtype=float32))

# PCA

In [71]:
imutils.find_function("pca")

1. PCABackProject
2. PCACompute
3. PCACompute2
4. PCAProject
5. PCA_DATA_AS_COL
6. PCA_DATA_AS_ROW
7. PCA_USE_AVG


In [ ]:
cv2.PCACompute2()