# numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

> - python list는 linked list 형태인데 numpy는 memory에 연속적으로 저장하므로 메모리 저장 방식을 바꾸는 경우에서 시간이 걸리는 경우가 있다.
- 간단한 연산의 경우는 메모리 저장 구조를 바꾸는 과정에서 시간이 들어서 numpy가 오히려 느린 경우가 가끔 있다.

# newaxis

In [4]:
np.newaxis

> return이 아무것도 없다 -> `None`

In [5]:
a[np.newaxis]

array([[1, 2, 3, 4, 5]])

> 차원이 늘어났다.

In [6]:
a[None]

array([[1, 2, 3, 4, 5]])

In [7]:
None is np.newaxis

True

> - `np.newaxis`는 `None`과 같다.
- `None`을 차원을 늘리도록 만들었는데, 사용자들이 어렵다는 항의가 많았다. 
- 직관적인 이해를 위해서 `np.newaxis`를 만들게 되었다.

In [8]:
a.shape

(5,)

In [9]:
a[np.newaxis].shape

(1, 5)

> - 차원이 늘어났으므로 shape이 바뀐다.

In [10]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

In [15]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
b.shape

(2, 2, 2)

> - 괄호에 따라서 차원을 구분한다. 

In [16]:
x = np.arange(6).reshape(2,3)

In [19]:
x[np.newaxis].shape

(1, 2, 3)

In [17]:
x[:, np.newaxis].shape

(2, 1, 3)

In [18]:
x[:, :, np.newaxis].shape

(2, 3, 1)

> - `newaxis`를 어디에 추가하는에 따라서 차원이 추가되는 위치가 달라진다.
- `:`도 연산자이다.
- `[]`를 쓰는 방법은 indexer라고 한다.

In [20]:
np.expand_dims(x, axis=0)

array([[[0, 1, 2],
        [3, 4, 5]]])

In [21]:
np.expand_dims(x, axis=0).shape

(1, 2, 3)

> - `np.newaxis` 대신에 차원을 늘리는 방법: `np.expand_dims`
- 좀더 사용하기 편하다.

# \_가 붙은 아이들

In [26]:
np.r_

> - shift + tab 해보면 "Signature" 가 없고 "RClass"라는 말이 있다.
- 심상치 않다.

In [29]:
# Error

np.r_(x)

TypeError: 'RClass' object is not callable

> - not callable이라고 하면 괄호를 사용할 수 없다.
- 사용방법이 다르다.

In [31]:
np.r_[x,x]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

> - row 별로 concatenate 시켜주는 기능이다.
- `()`이 아니라 `[]`를 써야함에 유의하자.

In [32]:
np.c_[x,x]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

> - `c_`는 column 별로 concatenate한다.

In [46]:
np.s_[:, 0:4:2]

(slice(None, None, None), slice(0, 4, 2))

In [45]:
x[np.s_[:, 0:4:2]]

array([[0, 2],
       [3, 5]])

> `s_`는 slice 객체를 만든다.

# stack

In [47]:
np.stack(x, 0)

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
np.stack((x, x), 0)

array([[[0, 1, 2],
        [3, 4, 5]],

       [[0, 1, 2],
        [3, 4, 5]]])

> - stack이 어떻게 합쳐주는지 잘 봐야한다.
- 괄호 모양을 보고 파악할 수 있다.

In [51]:
np.dstack([x,x])

array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4],
        [5, 5]]])

In [52]:
np.dstack((x,x)).shape

(2, 3, 2)

> - `dstack`은 마지막 차원을 추가해서 stack해줬다.
- annotation은 tuple을 넣으라고 하지만 list를 넣어도 되었다 => duck-typing

In [53]:
np.vstack((x,x))

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

> - `vstack`은 vertical로 쌓아준다.

In [54]:
np.hstack((x,x))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

> - `hstack`은 horizontal로 쌓아준다.

In [55]:
# default axis=None

np.append(x,x)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [56]:
np.append(x,x,0)

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [57]:
np.append(x,x,1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

> - `np.append`도 있다. 
- `axis=None`이면 차원을 통합한다.

In [58]:
from sklearn.model_selection import train_test_split
import inspect

In [59]:
print(inspect.getsource(train_test_split))

def train_test_split(*arrays, **options):
    """Split arrays or matrices into random train and test subsets

    Quick utility that wraps input validation and
    ``next(ShuffleSplit().split(X, y))`` and application to input data
    into a single call for splitting (and optionally subsampling) data in a
    oneliner.

    Read more in the :ref:`User Guide <cross_validation>`.

    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.

    test_size : float, int or None, optional (default=None)
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to the
        complement of the train size. If ``train_size`` is also None, it will
        be set to 0.25.

    train_size : float, int, or 

> - scikit learn의 내부구조를 보면 numpy로 만들었다.

# transpose

In [60]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
x.T

array([[0, 3],
       [1, 4],
       [2, 5]])

> - `T`는 array를 전치시켜준다. 

In [62]:
np.moveaxis(x,0,1)

array([[0, 3],
       [1, 4],
       [2, 5]])

> `moveaxis`를 이용해서 직접 transpose시킬 수 있다.

# vectorize

In [64]:
@np.vectorize
def x(a, b):
    return a+b

In [65]:
x(1,2)

array(3)

> - array 프로그래밍이 익숙하지 않으면, vectorzie 데코레이터를 이용해서 속도를 빠르게 할 수 있다.
- 금융 쪽에서 많이 사용하지만 우리는 쓰지 않을 것이다.